### ISSUE TITLE
planning: Jan Theme Extensions API

### ISSUE THREAD

**Issue by dan-menlo** [menloresearch/jan#3600]
## Goal 

- Jan has a clear Themes API that users can easily configure to change app appearance
    - Themes are separate Github repos
    - Inspo: Obsidian, VSCode
- What do we need to change
    - Instead of Joi
    - Use a more standard library? e.g. shadcn

## Tasklist

- [ ] @urmauur to propose Themes API and framework
- [ ] To document in https://github.com/orgs/janhq/discussions/3566
- [ ] https://github.com/janhq/jan/issues/3100

**Comment by dan-homebrew** [comment]
@urmauur I'll be shifting this to Sprint 22, to allow you to focus on Ichigo Demo, Jan + Cortex sites

**Comment by imtuyethan** [comment]
We should assign this in sprint 25?

**Comment by louis-jan** [comment]
We'd like to close it. The theme and appearance should work very closely with the system and need to be carefully tested internally. For now, we're deprecating the theme extension API for a consistent UX.
