### ISSUE TITLE
roadmap: Jan implements `/assistants` that can have Tools

### ISSUE THREAD

**Issue by dan-menlo** [menloresearch/jan#4274]
## Goal 

- Assistants can use Tools
    - MCP called from `chat/completions`
    - We do not use Runs

### Frontend
- [ ] Deprecate assistant extension retrieval tool
- [ ] Use file_search and defile tool use

### Backend
- [ ] Support file_search tool & vectorDB
- [ ] Support `tools` in chat/completions (v1)
- [ ] Support /runs to process chat_completions itself (v2)

**Comment by louis-jan** [comment]
Tasklist is updated

**Comment by louis-menlo** [comment]
Dup: Now #4824
